---
- name: Установка bind на Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Обновить кэш пакетов
      apt:
        update_cache: yes
      become: yes

    - name: Установить
      apt:
        name: bind9
        state: present
      become: yes

