---
- name: Install Nginx
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Nginx package
      apt:
        name: nginx
        state: present

        shell: sudo rm /etc/nginx/sites-enabled/default


    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
